name: vl-yaml
base: core22
version: git
license: GPL-3.0
summary: Vulnlog YAML PoC
description: |
  A simple proof of concept CLI of the Vulnlog project to process YAML-based Vulnlog definitions.

grade: stable
confinement: strict

apps:
  vl-yaml:
    command: bin/vl-yaml
    plugs:
      - home

parts:
  vl-yaml:
    plugin: dump
    source: .
    organize:
      vl-yaml: bin/vl-yaml
    stage:
      - bin/vl-yaml
