---
include:
  releases:
    file: releases.vl.yml
    ref-ids:
      - &p803 product803
      - &p804 product804
  reporters:
    file: reporters.vl.yml
    pipeline-ref-ids:
      - &trivy trivy-pipeline
      - &owasp owasp-pipeline

vulnerabilities:
  - desc: Information leak via uninitialized stack contents in the rsync daemon.
    cwe: 908
    reports:
      - vuln-id: CVE-2024-12085
        #        reporter: trivy
        #        at: 2024-12-18
        on: [ *p803, *p804 ]
        suppression:
          - on: [ *p803, *p804 ]
            until: 2026-01-01
      - vuln-id: [ CVE-2024-12086, CVE-2024-12087 ]
        #        reporter: owasp
        #        at: 2024-12-18
        on: *p804
    analysis:
      - at: 2024-12-18
        verdict:
          not-affected:
            vex: Component not present
        reasoning:
          In a typical environment the ports necessary for rsync are not exposed to the internet.
          Furthermore, the above vulnerability only occurs in the rsync daemon, which by default
          does not run on the product Docker container. Therefore, product is not affected.
          This vulnerability was reported in product 8.0.8, the latest publicly available version of
          the product 8.0 branch. The newest version of this branch, product 8.0.10, was released on
          2025-05-07, and no longer reports this vulnerability.
    resolutions:
      - accept:
          note: This is a test note.
      - update:
          note: This is another test note.
          maven-dependency: foo:bar:1.2.3
          to: 1.2.4
          resolved-at: 2025-04-29
