---
vulnlog:
  version: 1.0.0
  vendor: Company ABC
  product: Product ABC

include:
  releases:
    file: releases.vl.yml
  reporters:
    file: reporters.vl.yml

vulnerabilities:

  - desc: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    cwe: 1337
    reports:
      - vuln-id: CVE-2025-1234
        on-id: v100
        at: 2025-10-31
        reporters:
          - reporter12: myTrivy
            suppression:
              purls:
                - pkg:deb/debian/libssl1.1
          - reporter12: mySnyk
            suppression:
              paths:
                - foo/bar/baz1.jar
                - foo/bar/baz2.jar
                - foo/bar/baz3.jar
                - foo/bar/baz4.jar
    analysis:
      - on-id: v100
        at: 2025-11-01
        verdict:
          affected:
            severity: Critical
        reasoning: Product is affected.
    resolutions:
      - update:
          on-id: v100
          maven-dependency: foo:bar:1.2.3
          to: 1.2.4
          resolved-at: 2025-11-01

#  - desc: Information leak via uninitialized stack contents in the rsync daemon.
#    cwe: 908
#    reports:
#      - vuln-id: CVE-2024-12085
#        reporter-id: *trivy
#        at: 2024-12-18
#        on-id: [ *p805, *p832 ]
#        suppression:
#          - on-id: [ *p805, *p832 ]
#            until: 2026-01-01
#            trivy:
#              paths:
#                - /usr/bin/rsync
#              purls:
#                - pkg:deb/debian/libssl1.1
#      - vuln-id: [ CVE-2024-12086, CVE-2024-12087 ]
#        reporter-id: *owasp
#        at: 2024-12-18
#        on-id: *p805
#    analysis:
#      - at: 2024-12-18
#        verdict:
#          not-affected:
#            vex: Component not present
#        reasoning:
#          In a typical environment the ports necessary for rsync are not exposed to the internet.
#          Furthermore, the above vulnerability only occurs in the rsync daemon, which by default
#          does not run on the product Docker container. Therefore, product is not affected.
#          This vulnerability was reported in product 8.0.8, the latest publicly available version of
#          the product 8.0 branch. The newest version of this branch, product 8.0.10, was released on
#          2025-05-07, and no longer reports this vulnerability.
#    resolutions:
#      - accept:
#          note: This is a test note.
#      - update:
#          note: This is another test note.
#          maven-dependency: foo:bar:1.2.3
#          to: 1.2.4
#          on-id: *p832
#          resolved-at: 2025-04-29
#
#  - reports:
#      - vuln-id: CVE-2025-31257
#        on-id: [ *p7712, *p814, *p832, *p841, *p850, *p860 ]
#        reporter-id: *oracleCpu
#        at: 2025-10-23
#    analysis:
#      - verdict:
#          not-affected:
#            vex: Component not present
#        reasoning: Product does not use JavaFX and therefore does not have this vulnerability.
#
#  - reports:
#      - vuln-id: CVE-2025-53066
#        on-id: [ *p7712, *p814, *p832, *p841, *p850, *p860 ]
#        reporter-id: *oracleCpu
#        at: 2025-10-23
#
#  - reports:
#      - vuln-id: CVE-2025-53057
#        on-id: [ *p7712, *p814, *p832, *p841, *p850, *p860 ]
#        reporter-id: *oracleCpu
#        at: 2025-10-23
#
#  - cwe: 862
#    desc: Successful attacks of this vulnerability can result in unauthorized read access to a subset of Oracle GraalVM for JDK accessible data.
#    reports:
#      - vuln-id: CVE-2025-61755
#        on-id: [ *p7712, *p814, *p832, *p841, *p850, *p860 ]
#        reporter-id: *oracleCpu
#        at: 2025-10-23
#    analysis:
#      - verdict:
#          not-affected:
#            vex: Component not present
#        reasoning: Product does not use GraalVM and therefore does not have this vulnerability.
#
#
#
#  - reports:
#      - vuln-id: CVE-2025-61748
#        on-id: [ *p832, *p841, *p850, *p860 ]
#        reporter-id: *oracleCpu
#        at: 2025-10-23
