name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          architecture: x64
      - uses: gradle/actions/setup-gradle@v3
      - uses: sourcemeta/jsonschema@v11.11.1
      - run: ./gradlew check
